import math


class ModelConfig(object):

    INPUT_X_SIZE = 30
    INPUT_Y_SIZE = 30
    INPUT_SIZE = INPUT_X_SIZE * INPUT_Y_SIZE
    INPUT_CHANNEL = 3

    OUTPUT_SIZE = 2

    LAYER1_SIZE = 300
    LAYER1_CHANNEL = 10

    LAYER2_SIZE = 200
    LAYER2_CHANNEL = 40

    LAYER3_SIZE = 300
    LAYER3_CHANNEL = 1

    FILTER_SIZE = 5

    CONVOLUTIONAL_STRIDES = 1

    MAX_POOLING_STRIDES = 2

    CONVOLUTIONAL_LAYER_SIZE = 3

    FULLY_CONNECTED_INPUT_SIZE = INPUT_SIZE / (math.pow(MAX_POOLING_STRIDES, CONVOLUTIONAL_LAYER_SIZE))

    FULLY_CONNECTED_OUT_SIZE = INPUT_SIZE

    OUT_LAYER_INPUT_SIZE = FULLY_CONNECTED_OUT_SIZE
    OUT_LAYER_OUT_SIZE = OUTPUT_SIZE

    DROPOUT_PROBABILITY = 0.01

    LEARNING_RATE = 0.01
    BATCH_SIZE = 100






